server:
  port: 8081
spring:
  application:
    name: wallet-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/walletDb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
  security:
    user:
      name: user
      password: user

jwt:
 secret: bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OQ==
 expiration: 11000000   # 3.05 hrs in milliseconds

#user1
#password123

